// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhZxoSWIaKeMeBpPWoDAKb1zswoeOBSQ',
    appId: '1:337157647716:web:96d2ad3038c8bf074e1e71',
    messagingSenderId: '337157647716',
    projectId: 'integrador-2d81b',
    authDomain: 'integrador-2d81b.firebaseapp.com',
    storageBucket: 'integrador-2d81b.appspot.com',
    measurementId: 'G-SG6MV6J0TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXLW590IHGj-30cVNf18ktr7KqrQOlTc',
    appId: '1:337157647716:android:9f21c48c61eb4bd64e1e71',
    messagingSenderId: '337157647716',
    projectId: 'integrador-2d81b',
    storageBucket: 'integrador-2d81b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZhZxoSWIaKeMeBpPWoDAKb1zswoeOBSQ',
    appId: '1:337157647716:web:e7cd7ef9dce663614e1e71',
    messagingSenderId: '337157647716',
    projectId: 'integrador-2d81b',
    authDomain: 'integrador-2d81b.firebaseapp.com',
    storageBucket: 'integrador-2d81b.appspot.com',
    measurementId: 'G-JTB5QFM2BG',
  );
}